
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Sun Apr 23 21:32:42 EET 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int REL_OP = 20;
  public static final int INCREMENT = 47;
  public static final int CONST = 11;
  public static final int SLASH = 42;
  public static final int CDOTS = 37;
  public static final int CASE = 6;
  public static final int CLOSE_SQUARE = 30;
  public static final int DECREMENT = 48;
  public static final int FOR = 14;
  public static final int MINUS = 23;
  public static final int BAR = 41;
  public static final int TYPE = 13;
  public static final int ASTRISK = 38;
  public static final int OPEN_PARAN = 25;
  public static final int LESS_DASH = 44;
  public static final int COMMA = 32;
  public static final int OPEN_SQUARE = 29;
  public static final int OR_OP = 18;
  public static final int OPEN_CURLY = 27;
  public static final int PLUS = 22;
  public static final int AMBERSAND = 45;
  public static final int EXCLAMATION = 43;
  public static final int IF = 12;
  public static final int DOT = 33;
  public static final int AND_OP = 19;
  public static final int EOF = 0;
  public static final int RETURN = 16;
  public static final int EQUAL = 36;
  public static final int error = 1;
  public static final int PERCENT = 46;
  public static final int SEMI_COLON = 31;
  public static final int BREAK = 3;
  public static final int ERROR = 49;
  public static final int SHIFT_LEFT = 39;
  public static final int SWITCH = 10;
  public static final int CLOSE_PARAN = 26;
  public static final int IMPORT = 15;
  public static final int COLON = 34;
  public static final int CLOSE_CURLY = 28;
  public static final int ELSE = 8;
  public static final int FUNC = 5;
  public static final int PACKAGE = 9;
  public static final int DEFAULT = 4;
  public static final int STRUCT = 7;
  public static final int STRING_LIT = 24;
  public static final int SHIFT_RIGHT = 40;
  public static final int INT_LIT = 21;
  public static final int COLON_EQUAL = 35;
  public static final int VAR = 17;
  public static final int IDENTIFIER = 2;
}

